apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: educode
    releaseName: educode
    namespace: educode
    version: 14.0.0
    repo: file://../../kubernetes/helm
    valuesFile: values.yaml
