"""Biblioteca institucional de elementos e personagens gerados.

Revision ID: 0017_institutional_asset_library
Revises: 0016_learning_analytics
Create Date: 2026-07-22
"""
from collections.abc import Sequence
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision="0017_institutional_asset_library"
down_revision="0016_learning_analytics"
branch_labels: str | Sequence[str] | None=None
depends_on: str | Sequence[str] | None=None

asset_type=postgresql.ENUM("CHARACTER","SCENE","OBJECT","BACKGROUND","ANIMAL","VEHICLE","FURNITURE","CLOTHING","ACCESSORY","EFFECT","BALLOON","ICON","FRAME","COVER","PAGE_LAYOUT","PALETTE","LOGO","OTHER",name="institutional_asset_type",create_type=False)
asset_status=postgresql.ENUM("DRAFT","PROCESSING","IN_REVIEW","APPROVED","PUBLISHED","REJECTED","OBSOLETE","BLOCKED","ARCHIVED",name="institutional_asset_status",create_type=False)
asset_visibility=postgresql.ENUM("ORGANIZATION","SELECTED_TEACHERS","PROJECT_ONLY",name="institutional_asset_visibility",create_type=False)
license_type=postgresql.ENUM("PROPRIETARY","CC_BY","CC_BY_SA","PUBLIC_DOMAIN","AUTHORIZED_USE","OTHER",name="institutional_license_type",create_type=False)

def upgrade():
    bind=op.get_bind()
    for e in (asset_type,asset_status,asset_visibility,license_type): e.create(bind,checkfirst=True)
    op.create_table("institutional_assets",
        sa.Column("id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("asset_type",asset_type,nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("category",sa.String(120),server_default="Geral",nullable=False),sa.Column("subcategory",sa.String(120)),sa.Column("status",asset_status,server_default="DRAFT",nullable=False),sa.Column("visibility",asset_visibility,server_default="ORGANIZATION",nullable=False),sa.Column("current_version",sa.Integer(),server_default="1",nullable=False),sa.Column("metadata_json",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("compatibility",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("age_groups",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("subject_codes",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("canonical_prompt",sa.Text()),sa.Column("negative_prompt",sa.Text()),sa.Column("immutable_traits",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("license_type",license_type,server_default="AUTHORIZED_USE",nullable=False),sa.Column("original_author",sa.String(180)),sa.Column("attribution_text",sa.Text()),sa.Column("usage_restrictions",sa.Text()),sa.Column("rights_confirmed",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("is_real_person",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("consent_expires_at",sa.DateTime(timezone=True)),sa.Column("source_comic_id",sa.Uuid()),sa.Column("source_page_id",sa.Uuid()),sa.Column("source_panel_id",sa.Uuid()),sa.Column("source_creative_item_id",sa.Uuid()),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("approved_by_user_id",sa.Uuid()),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["source_comic_id"],["generated_comics.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["source_page_id"],["comic_pages.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["source_panel_id"],["comic_panels.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["source_creative_item_id"],["creative_items.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["approved_by_user_id"],["users.id"],ondelete="SET NULL"),sa.UniqueConstraint("organization_id","asset_type","name",name="uq_institutional_asset_name"))
    for c in ("organization_id","asset_type","category","subcategory","status","source_comic_id","created_by_user_id"): op.create_index(f"ix_institutional_assets_{c}","institutional_assets",[c])
    op.create_table("institutional_asset_variants",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("variant_type",sa.String(100),server_default="default",nullable=False),sa.Column("metadata_json",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("is_default",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="CASCADE"),sa.UniqueConstraint("asset_id","name",name="uq_institutional_asset_variant_name"));op.create_index("ix_institutional_asset_variants_asset_id","institutional_asset_variants",["asset_id"])
    op.create_table("institutional_asset_files",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("variant_id",sa.Uuid()),sa.Column("file_name",sa.String(255),nullable=False),sa.Column("mime_type",sa.String(120),nullable=False),sa.Column("storage_key",sa.String(500),nullable=False),sa.Column("checksum_sha256",sa.String(64),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("width",sa.Integer()),sa.Column("height",sa.Integer()),sa.Column("view_type",sa.String(80),server_default="reference",nullable=False),sa.Column("is_primary",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("is_original",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["variant_id"],["institutional_asset_variants.id"],ondelete="SET NULL"),sa.UniqueConstraint("storage_key"));op.create_index("ix_institutional_asset_files_asset_id","institutional_asset_files",["asset_id"]);op.create_index("ix_institutional_asset_files_checksum_sha256","institutional_asset_files",["checksum_sha256"])
    op.create_table("institutional_asset_versions",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("snapshot_json",sa.JSON(),nullable=False),sa.Column("change_description",sa.Text()),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"),sa.UniqueConstraint("asset_id","version_number",name="uq_institutional_asset_version"));op.create_index("ix_institutional_asset_versions_asset_id","institutional_asset_versions",["asset_id"])
    op.create_table("institutional_asset_tags",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("tag",sa.String(80),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="CASCADE"),sa.UniqueConstraint("asset_id","tag",name="uq_institutional_asset_tag"));op.create_index("ix_institutional_asset_tags_asset_id","institutional_asset_tags",["asset_id"]);op.create_index("ix_institutional_asset_tags_tag","institutional_asset_tags",["tag"])
    op.create_table("asset_collections",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("is_kit",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("metadata_json",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_asset_collections_organization_id","asset_collections",["organization_id"])
    op.create_table("asset_collection_items",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("collection_id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("position",sa.Integer(),server_default="0",nullable=False),sa.Column("is_required",sa.Boolean(),server_default=sa.false(),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["collection_id"],["asset_collections.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="CASCADE"),sa.UniqueConstraint("collection_id","asset_id",name="uq_asset_collection_item"));op.create_index("ix_asset_collection_items_collection_id","asset_collection_items",["collection_id"]);op.create_index("ix_asset_collection_items_asset_id","asset_collection_items",["asset_id"])
    op.create_table("institutional_asset_usages",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid(),nullable=False),sa.Column("asset_version",sa.Integer(),nullable=False),sa.Column("comic_id",sa.Uuid()),sa.Column("panel_id",sa.Uuid()),sa.Column("used_by_user_id",sa.Uuid(),nullable=False),sa.Column("used_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["comic_id"],["generated_comics.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["panel_id"],["comic_panels.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["used_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_institutional_asset_usages_organization_id","institutional_asset_usages",["organization_id"]);op.create_index("ix_institutional_asset_usages_asset_id","institutional_asset_usages",["asset_id"]);op.create_index("ix_institutional_asset_usages_comic_id","institutional_asset_usages",["comic_id"])
    op.create_table("institutional_asset_audit",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("asset_id",sa.Uuid()),sa.Column("actor_user_id",sa.Uuid(),nullable=False),sa.Column("action",sa.String(100),nullable=False),sa.Column("details",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["asset_id"],["institutional_assets.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["actor_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_institutional_asset_audit_organization_id","institutional_asset_audit",["organization_id"]);op.create_index("ix_institutional_asset_audit_asset_id","institutional_asset_audit",["asset_id"]);op.create_index("ix_institutional_asset_audit_action","institutional_asset_audit",["action"])

def downgrade():
    for table in ("institutional_asset_audit","institutional_asset_usages","asset_collection_items","asset_collections","institutional_asset_tags","institutional_asset_versions","institutional_asset_files","institutional_asset_variants","institutional_assets"): op.drop_table(table)
    bind=op.get_bind()
    for e in (license_type,asset_visibility,asset_status,asset_type): e.drop(bind,checkfirst=True)
