"""Laboratório Estatístico Educacional.

Revision ID: 0018_statistical_research_lab
Revises: 0017_institutional_asset_library
Create Date: 2026-07-22
"""
from collections.abc import Sequence
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision="0018_statistical_research_lab"
down_revision="0017_institutional_asset_library"
branch_labels: str | Sequence[str] | None=None
depends_on: str | Sequence[str] | None=None

study_status=postgresql.ENUM("DRAFT","ACTIVE","IN_REVIEW","APPROVED","ARCHIVED",name="statistical_study_status",create_type=False)
dataset_status=postgresql.ENUM("BUILDING","FROZEN","INVALID",name="statistical_dataset_status",create_type=False)
analysis_status=postgresql.ENUM("PENDING","COMPLETED","FAILED","IN_REVIEW","APPROVED",name="statistical_analysis_status",create_type=False)
report_type=postgresql.ENUM("TEACHER","STATISTICAL","ACADEMIC",name="statistical_report_type",create_type=False)

def upgrade():
    bind=op.get_bind()
    for enum in (study_status,dataset_status,analysis_status,report_type): enum.create(bind,checkfirst=True)
    op.create_table("statistical_studies",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("research_question",sa.Text(),server_default="",nullable=False),sa.Column("null_hypothesis",sa.Text(),server_default="",nullable=False),sa.Column("alternative_hypothesis",sa.Text(),server_default="",nullable=False),sa.Column("study_design",sa.String(80),server_default="pre_post",nullable=False),sa.Column("significance_level",sa.Float(),server_default="0.05",nullable=False),sa.Column("pedagogical_threshold",sa.Float()),sa.Column("status",study_status,server_default="DRAFT",nullable=False),sa.Column("settings",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_statistical_studies_organization_id","statistical_studies",["organization_id"])
    op.create_table("statistical_datasets",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("status",dataset_status,server_default="BUILDING",nullable=False),sa.Column("snapshot_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("filters",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("attempt_policy",sa.String(30),server_default="first",nullable=False),sa.Column("participant_count",sa.Integer(),server_default="0",nullable=False),sa.Column("row_count",sa.Integer(),server_default="0",nullable=False),sa.Column("dataset_checksum",sa.String(64),nullable=False),sa.Column("quality_summary",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("variable_dictionary",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("rows_snapshot",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("anonymized",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["study_id"],["statistical_studies.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_statistical_datasets_study_id","statistical_datasets",["study_id"]);op.create_index("ix_statistical_datasets_organization_id","statistical_datasets",["organization_id"])
    op.create_table("statistical_analyses",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("dataset_id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("analysis_type",sa.String(80),nullable=False),sa.Column("parameters",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("assumptions",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("descriptive_results",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("test_results",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("effect_size",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("confidence_intervals",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("interpretation_teacher",sa.Text(),server_default="",nullable=False),sa.Column("interpretation_researcher",sa.Text(),server_default="",nullable=False),sa.Column("limitations",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("software_versions",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("status",analysis_status,server_default="PENDING",nullable=False),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("executed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["study_id"],["statistical_studies.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["dataset_id"],["statistical_datasets.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_statistical_analyses_study_id","statistical_analyses",["study_id"]);op.create_index("ix_statistical_analyses_dataset_id","statistical_analyses",["dataset_id"]);op.create_index("ix_statistical_analyses_organization_id","statistical_analyses",["organization_id"]);op.create_index("ix_statistical_analyses_analysis_type","statistical_analyses",["analysis_type"])
    op.create_table("statistical_charts",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("analysis_id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("chart_type",sa.String(60),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("description",sa.Text(),server_default="",nullable=False),sa.Column("configuration",sa.JSON(),server_default=sa.text("'{}'::json"),nullable=False),sa.Column("data_snapshot",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("alt_text",sa.Text(),server_default="",nullable=False),sa.Column("display_order",sa.Integer(),server_default="0",nullable=False),sa.Column("include_in_report",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["analysis_id"],["statistical_analyses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"));op.create_index("ix_statistical_charts_analysis_id","statistical_charts",["analysis_id"])
    op.create_table("statistical_reports",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("analysis_id",sa.Uuid(),nullable=False),sa.Column("organization_id",sa.Uuid(),nullable=False),sa.Column("report_type",report_type,nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("content_html",sa.Text(),nullable=False),sa.Column("sections",sa.JSON(),server_default=sa.text("'[]'::json"),nullable=False),sa.Column("version_number",sa.Integer(),server_default="1",nullable=False),sa.Column("review_status",sa.String(40),server_default="draft",nullable=False),sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.PrimaryKeyConstraint("id"),sa.ForeignKeyConstraint(["study_id"],["statistical_studies.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["analysis_id"],["statistical_analyses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"));op.create_index("ix_statistical_reports_study_id","statistical_reports",["study_id"]);op.create_index("ix_statistical_reports_analysis_id","statistical_reports",["analysis_id"])

def downgrade():
    for table in ("statistical_reports","statistical_charts","statistical_analyses","statistical_datasets","statistical_studies"): op.drop_table(table)
    bind=op.get_bind()
    for enum in (report_type,analysis_status,dataset_status,study_status): enum.drop(bind,checkfirst=True)
