"""AI Fabric advanced workflows.
Revision ID: 0022_ai_fabric_advanced_flow
Revises: 0021_ai_orchestration_runtime
Create Date: 2026-07-23
"""
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
revision="0022_ai_fabric_advanced_flow"
down_revision="0021_ai_orchestration_runtime"
branch_labels: str|Sequence[str]|None=None
depends_on: str|Sequence[str]|None=None
E=sa.text("'{}'::json");L=sa.text("'[]'::json");N=sa.text('now()')
def upgrade():
 op.create_table('ai_project_memories',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('project_id',sa.Uuid(),nullable=False),sa.Column('memory_version',sa.Integer(),server_default='1',nullable=False),sa.Column('objectives',sa.JSON(),server_default=L,nullable=False),sa.Column('audience_profile',sa.JSON(),server_default=E,nullable=False),sa.Column('tone_rules',sa.JSON(),server_default=E,nullable=False),sa.Column('canonical_characters',sa.JSON(),server_default=L,nullable=False),sa.Column('visual_rules',sa.JSON(),server_default=E,nullable=False),sa.Column('approved_decisions',sa.JSON(),server_default=L,nullable=False),sa.Column('forbidden_changes',sa.JSON(),server_default=L,nullable=False),sa.Column('updated_by_user_id',sa.Uuid(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['project_id'],['projects.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['updated_by_user_id'],['users.id'],ondelete='RESTRICT'),sa.UniqueConstraint('organization_id','project_id',name='uq_ai_memory_org_project'))
 op.create_index('ix_ai_project_memories_organization_id','ai_project_memories',['organization_id']);op.create_index('ix_ai_project_memories_project_id','ai_project_memories',['project_id'])
 op.create_table('ai_review_queue_items',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('request_id',sa.Uuid(),nullable=False),sa.Column('result_id',sa.Uuid(),nullable=False),sa.Column('module_name',sa.String(80),nullable=False),sa.Column('priority',sa.Integer(),server_default='50',nullable=False),sa.Column('status',sa.String(30),server_default='pending',nullable=False),sa.Column('quality_score',sa.Float(),server_default='0',nullable=False),sa.Column('reasons',sa.JSON(),server_default=L,nullable=False),sa.Column('assigned_to_user_id',sa.Uuid()),sa.Column('due_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['request_id'],['ai_generation_requests.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['result_id'],['ai_generation_results.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['assigned_to_user_id'],['users.id'],ondelete='SET NULL'),sa.UniqueConstraint('organization_id','result_id',name='uq_ai_review_queue_org_result'))
 for c in ('organization_id','request_id','result_id','module_name','status'):op.create_index(f'ix_ai_review_queue_items_{c}','ai_review_queue_items',[c])
 op.create_table('ai_quality_evaluations',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('result_id',sa.Uuid(),nullable=False),*[sa.Column(n,sa.Float(),server_default='0',nullable=False) for n in ('structural_validity','pedagogical_alignment','source_coverage','age_appropriateness','narrative_consistency','safety_score','confidence_score')],sa.Column('findings',sa.JSON(),server_default=L,nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['result_id'],['ai_generation_results.id'],ondelete='CASCADE'))
 op.create_index('ix_ai_quality_evaluations_organization_id','ai_quality_evaluations',['organization_id']);op.create_index('ix_ai_quality_evaluations_result_id','ai_quality_evaluations',['result_id'])
 op.create_table('ai_model_comparisons',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('flow_id',sa.String(64),nullable=False),sa.Column('module_name',sa.String(80),nullable=False),sa.Column('action_name',sa.String(100),nullable=False),sa.Column('input_snapshot',sa.JSON(),server_default=E,nullable=False),sa.Column('model_ids',sa.JSON(),server_default=L,nullable=False),sa.Column('comparison_results',sa.JSON(),server_default=L,nullable=False),sa.Column('recommended_model_id',sa.Uuid()),sa.Column('created_by_user_id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['recommended_model_id'],['ai_models.id'],ondelete='SET NULL'),sa.ForeignKeyConstraint(['created_by_user_id'],['users.id'],ondelete='RESTRICT'))
 op.create_index('ix_ai_model_comparisons_organization_id','ai_model_comparisons',['organization_id']);op.create_index('ix_ai_model_comparisons_flow_id','ai_model_comparisons',['flow_id'])
 op.create_table('ai_generation_checkpoints',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('request_id',sa.Uuid(),nullable=False),sa.Column('step_key',sa.String(100),nullable=False),sa.Column('step_order',sa.Integer(),nullable=False),sa.Column('status',sa.String(30),server_default='completed',nullable=False),sa.Column('payload_snapshot',sa.JSON(),server_default=E,nullable=False),sa.Column('checksum',sa.String(64),server_default='',nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['request_id'],['ai_generation_requests.id'],ondelete='CASCADE'),sa.UniqueConstraint('request_id','step_key',name='uq_ai_checkpoint_request_step'))
 op.create_index('ix_ai_generation_checkpoints_organization_id','ai_generation_checkpoints',['organization_id']);op.create_index('ix_ai_generation_checkpoints_request_id','ai_generation_checkpoints',['request_id'])
 op.create_table('ai_accessibility_artifacts',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),nullable=False),sa.Column('result_id',sa.Uuid(),nullable=False),sa.Column('artifact_type',sa.String(60),nullable=False),sa.Column('locale',sa.String(20),server_default='pt-BR',nullable=False),sa.Column('content',sa.JSON(),server_default=E,nullable=False),sa.Column('validated',sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column('created_by_user_id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=N,nullable=False),sa.ForeignKeyConstraint(['organization_id'],['organizations.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['result_id'],['ai_generation_results.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['created_by_user_id'],['users.id'],ondelete='RESTRICT'))
 for c in ('organization_id','result_id','artifact_type'):op.create_index(f'ix_ai_accessibility_artifacts_{c}','ai_accessibility_artifacts',[c])
def downgrade():
 for t in ('ai_accessibility_artifacts','ai_generation_checkpoints','ai_model_comparisons','ai_quality_evaluations','ai_review_queue_items','ai_project_memories'):op.drop_table(t)
