import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api } from '../lib/api'
import type { AssetStatus, AssetType, InstitutionalAsset } from '../types/assets'

const labels: Record<AssetType,string>={character:'Personagens',scene:'Cenários',object:'Objetos',background:'Fundos',animal:'Animais',vehicle:'Veículos',furniture:'Móveis',clothing:'Roupas',accessory:'Acessórios',effect:'Efeitos',balloon:'Balões',icon:'Ícones',frame:'Molduras',cover:'Capas',page_layout:'Layouts',palette:'Paletas',logo:'Logotipos',other:'Outros'}
const types=Object.keys(labels) as AssetType[]
export function AdminAssetLibraryPage(){
 const [items,setItems]=useState<InstitutionalAsset[]>([]),[query,setQuery]=useState(''),[type,setType]=useState<AssetType|'all'>('all'),[selected,setSelected]=useState<InstitutionalAsset|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({asset_type:'character' as AssetType,name:'',description:'',category:'Geral',tags:'',compatibility:'hq,storyboard',age_groups:'anos finais',original_author:'',rights_confirmed:false})
 async function load(){try{setItems(await api<InstitutionalAsset[]>(`/admin/assets?q=${encodeURIComponent(query)}${type==='all'?'':`&asset_type=${type}`}`))}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar')}}
 useEffect(()=>{void load()},[type])
 const stats=useMemo(()=>({total:items.length,published:items.filter(i=>i.status==='published').length,review:items.filter(i=>i.status==='in_review').length,files:items.reduce((s,i)=>s+i.files.length,0)}),[items])
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/admin/assets',{method:'POST',body:JSON.stringify({...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),compatibility:form.compatibility.split(',').map(x=>x.trim()).filter(Boolean),age_groups:form.age_groups.split(',').map(x=>x.trim()).filter(Boolean),metadata_json:{},subject_codes:[],immutable_traits:[],license_type:'authorized_use',visibility:'organization'})});setForm({...form,name:'',description:'',tags:''});await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao cadastrar')}finally{setBusy(false)}}
 async function status(item:InstitutionalAsset,s:AssetStatus){await api(`/admin/assets/${item.id}/status`,{method:'POST',body:JSON.stringify({status:s})});await load()}
 async function upload(item:InstitutionalAsset,file:File){const fd=new FormData();fd.append('file',file);fd.append('view_type','reference');fd.append('is_primary',String(item.files.length===0));await api(`/admin/assets/${item.id}/files`,{method:'POST',body:fd});await load()}
 return <section><header className="page-header"><div><span className="eyebrow">Administração</span><h1>Biblioteca institucional de elementos</h1><p>Personagens, cenários, objetos e recursos liberados para os professores.</p></div></header>
 {error&&<div className="alert error">{error}</div>}
 <div className="stats-grid"><div className="stat-card"><strong>{stats.total}</strong><span>elementos</span></div><div className="stat-card"><strong>{stats.published}</strong><span>publicados</span></div><div className="stat-card"><strong>{stats.review}</strong><span>em revisão</span></div><div className="stat-card"><strong>{stats.files}</strong><span>arquivos</span></div></div>
 <div className="two-column-grid"><form className="panel" onSubmit={create}><h2>Novo elemento</h2><label>Tipo<select value={form.asset_type} onChange={e=>setForm({...form,asset_type:e.target.value as AssetType})}>{types.map(t=><option value={t} key={t}>{labels[t]}</option>)}</select></label><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="ciências, anime, laboratório"/></label><label>Compatibilidade<input value={form.compatibility} onChange={e=>setForm({...form,compatibility:e.target.value})}/></label><label>Faixas etárias<input value={form.age_groups} onChange={e=>setForm({...form,age_groups:e.target.value})}/></label><label>Autor original<input value={form.original_author} onChange={e=>setForm({...form,original_author:e.target.value})}/></label><label className="checkbox-row"><input type="checkbox" checked={form.rights_confirmed} onChange={e=>setForm({...form,rights_confirmed:e.target.checked})}/>Confirmo os direitos de uso</label><button disabled={busy}>Cadastrar</button></form>
 <div className="panel"><h2>Pesquisar</h2><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, categoria ou descrição"/><button onClick={()=>void load()}>Buscar</button></div><select value={type} onChange={e=>setType(e.target.value as AssetType|'all')}><option value="all">Todos os tipos</option>{types.map(t=><option value={t} key={t}>{labels[t]}</option>)}</select><div className="card-list">{items.map(item=><article className="content-card" key={item.id} onClick={()=>setSelected(item)}><div><span className="status-chip">{labels[item.asset_type]}</span><h3>{item.name}</h3><p>{item.description||'Sem descrição'}</p><small>{item.category} · v{item.current_version} · {item.files.length} arquivo(s)</small></div><strong>{item.status}</strong></article>)}</div></div></div>
 {selected&&<div className="panel"><div className="section-heading"><div><h2>{selected.name}</h2><p>{selected.tags.join(' · ')}</p></div><button className="secondary" onClick={()=>setSelected(null)}>Fechar</button></div><div className="toolbar"><label className="button-like">Enviar imagem/PDF<input hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(selected,f)}}/></label>{selected.status!=='published'&&<button onClick={()=>void status(selected,'published')}>Publicar</button>}<button className="secondary" onClick={()=>void status(selected,'archived')}>Arquivar</button></div><p><strong>Licença:</strong> {selected.license_type}</p><p><strong>Compatibilidade:</strong> {selected.compatibility.join(', ')||'não informada'}</p><div className="asset-grid">{selected.files.map(f=><div className="asset-card" key={f.id}><strong>{f.file_name}</strong><small>{Math.round(f.size_bytes/1024)} KB · {f.view_type}</small></div>)}</div></div>}
 </section>
}
