import { FormEvent, useEffect, useState } from 'react'
import { api } from '../lib/api'
type QueueItem={id:string;module_name:string;priority:number;status:string;quality_score:number;reasons:string[]}
type Metrics={total_results:number;approved:number;rejected:number;approval_rate:number;average_quality:number;average_human_rating:number;estimated_cost:number}
export function AIAdvancedPage(){
 const [queue,setQueue]=useState<QueueItem[]>([]);const [metrics,setMetrics]=useState<Metrics|null>(null);const [projectId,setProjectId]=useState('');const [message,setMessage]=useState('')
 async function load(){const [q,m]=await Promise.all([api<QueueItem[]>('/ai/advanced/review-queue'),api<Metrics>('/ai/advanced/value-metrics')]);setQueue(q);setMetrics(m)}
 useEffect(()=>{void load()},[])
 async function saveMemory(e:FormEvent){e.preventDefault();if(!projectId)return;await api(`/ai/advanced/project-memories/${projectId}`,{method:'PUT',body:JSON.stringify({objectives:['Criar materiais alinhados à BNCC e ao Pensamento Computacional'],audience_profile:{language:'pt-BR'},tone_rules:{style:'claro, criativo e adequado à idade'},canonical_characters:[],visual_rules:{editable_text:true},approved_decisions:[],forbidden_changes:['Não alterar características imutáveis dos personagens']})});setMessage('Memória do projeto versionada.');}
 async function update(id:string,status:string){await api(`/ai/advanced/review-queue/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}
 return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">Sprint 12.1</span><h1>AI Fabric avançado</h1><p>Memória de projeto, revisão humana, qualidade, continuidade, acessibilidade e retomada segura.</p></div></header>{message?<div className="notice success">{message}</div>:null}
 <section className="panel-grid two"><section className="panel"><h2>Métricas de valor</h2>{metrics?<div className="metric-grid"><article><strong>{metrics.total_results}</strong><span>Resultados</span></article><article><strong>{Math.round(metrics.approval_rate*100)}%</strong><span>Aprovação</span></article><article><strong>{Math.round(metrics.average_quality*100)}%</strong><span>Qualidade</span></article><article><strong>{metrics.estimated_cost.toFixed(4)}</strong><span>Custo estimado</span></article></div>:<p>Carregando...</p>}</section>
 <form className="panel" onSubmit={saveMemory}><h2>Memória controlada do projeto</h2><label>ID do projeto<input value={projectId} onChange={e=>setProjectId(e.target.value)} placeholder="UUID do projeto" required/></label><p>Salva objetivos, público, tom, regras visuais, personagens canônicos e decisões aprovadas em uma versão auditável.</p><button type="submit">Criar ou atualizar memória</button></form></section>
 <section className="panel"><h2>Caixa de revisões humanas</h2><div className="card-list">{queue.length?queue.map(item=><article className="compact-card" key={item.id}><strong>{item.module_name} · prioridade {item.priority}</strong><span>Qualidade {Math.round(item.quality_score*100)}% · {item.status}</span><small>{item.reasons.join(' · ')||'Sem alertas adicionais'}</small><div className="button-row"><button onClick={()=>void update(item.id,'in_review')} type="button">Assumir revisão</button><button onClick={()=>void update(item.id,'approved')} type="button">Aprovar</button><button className="secondary" onClick={()=>void update(item.id,'changes_requested')} type="button">Solicitar ajustes</button></div></article>):<p>Nenhum item aguardando revisão.</p>}</div></section>
 <section className="panel"><h2>Recursos integrados</h2><div className="card-list"><article className="compact-card"><strong>Continuidade narrativa</strong><span>Compara HQs com personagens e regras canônicas.</span></article><article className="compact-card"><strong>Comparação de modelos</strong><span>Avalia aderência estrutural, qualidade, latência e custo.</span></article><article className="compact-card"><strong>Retomada por checkpoints</strong><span>Continua fluxos longos sem refazer etapas válidas.</span></article><article className="compact-card"><strong>Acessibilidade</strong><span>Gera texto alternativo, versão simplificada e resumo para leitor de tela.</span></article></div></section></div>
}
