from __future__ import annotations

REVIEW_SESSION_STATUSES = {
    "DRAFT", "OPEN", "IN_REVIEW", "CHANGES_REQUESTED", "APPROVED", "CLOSED", "CANCELLED"
}
THREAD_STATUSES = {"OPEN", "RESOLVED", "REOPENED"}
ANCHOR_TYPES = {"PROJECT", "PAGE", "PANEL", "LAYER"}
ASSIGNMENT_ROLES = {
    "AUTHOR", "PEDAGOGICAL_REVIEWER", "BNCC_REVIEWER", "ACCESSIBILITY_REVIEWER",
    "VISUAL_REVIEWER", "LEGAL_REVIEWER", "EDITOR", "APPROVER"
}
DECISIONS = {"APPROVE", "REQUEST_CHANGES", "REJECT", "ABSTAIN"}
CHANGE_REQUEST_STATUSES = {"OPEN", "ACCEPTED", "REJECTED", "IMPLEMENTED", "CANCELLED"}
CHECKLIST_CATEGORIES = {"PEDAGOGICAL", "BNCC", "ACCESSIBILITY", "VISUAL", "LEGAL", "PUBLICATION"}
RELEASE_STATUSES = {"DRAFT", "READY", "SCHEDULED", "PUBLISHED", "WITHDRAWN", "ARCHIVED"}
TARGET_TYPES = {"CLASSROOM", "GROUP", "STUDENT", "INSTITUTIONAL_LIBRARY", "PUBLIC_CATALOG"}
