from __future__ import annotations

from enum import StrEnum


class HintLevel(StrEnum):
    ORIENTATION = "ORIENTATION"
    STRATEGY = "STRATEGY"
    SPECIFIC = "SPECIFIC"
    SIMILAR_EXAMPLE = "SIMILAR_EXAMPLE"
    GUIDED_SOLUTION = "GUIDED_SOLUTION"


HINT_LEVEL_ORDER: dict[HintLevel, int] = {
    HintLevel.ORIENTATION: 1,
    HintLevel.STRATEGY: 2,
    HintLevel.SPECIFIC: 3,
    HintLevel.SIMILAR_EXAMPLE: 4,
    HintLevel.GUIDED_SOLUTION: 5,
}


class HintReleaseType(StrEnum):
    MANUAL = "MANUAL"
    AFTER_INCORRECT = "AFTER_INCORRECT"
    TIMEOUT = "TIMEOUT"
    ERROR_PATTERN = "ERROR_PATTERN"
    DOMAIN_RULE = "DOMAIN_RULE"
    ACCESSIBILITY = "ACCESSIBILITY"


class ReviewStatus(StrEnum):
    NOT_SCHEDULED = "NOT_SCHEDULED"
    FUTURE = "FUTURE"
    UPCOMING = "UPCOMING"
    AVAILABLE = "AVAILABLE"
    OVERDUE = "OVERDUE"
    COMPLETED = "COMPLETED"
    DISMISSED = "DISMISSED"
    SUSPENDED = "SUSPENDED"


class FeedbackType(StrEnum):
    CORRECT_CONFIRMATION = "CORRECT_CONFIRMATION"
    ERROR_EXPLANATION = "ERROR_EXPLANATION"
    STRATEGY_GUIDANCE = "STRATEGY_GUIDANCE"
    CONCEPT_REINFORCEMENT = "CONCEPT_REINFORCEMENT"
    RETRY_ENCOURAGEMENT = "RETRY_ENCOURAGEMENT"
    ATTEMPT_COMPARISON = "ATTEMPT_COMPARISON"
    REVIEW_SUGGESTION = "REVIEW_SUGGESTION"
    METACOGNITIVE = "METACOGNITIVE"
    COMPUTATIONAL_THINKING = "COMPUTATIONAL_THINKING"
    ACCESSIBLE = "ACCESSIBLE"


class ErrorType(StrEnum):
    NONE = "NONE"
    CONCEPTUAL = "CONCEPTUAL"
    CALCULATION = "CALCULATION"
    INTERPRETATION = "INTERPRETATION"
    SEQUENCE = "SEQUENCE"
    REPRESENTATION = "REPRESENTATION"
    INCOMPLETE = "INCOMPLETE"
    RANDOM_CHOICE = "RANDOM_CHOICE"
    STRATEGY = "STRATEGY"
    ABSTRACTION = "ABSTRACTION"
    DECOMPOSITION = "DECOMPOSITION"
    ALGORITHMIC = "ALGORITHMIC"
    DEBUGGING = "DEBUGGING"


class DifficultyLevel(StrEnum):
    VERY_EASY = "VERY_EASY"
    EASY = "EASY"
    INTERMEDIATE = "INTERMEDIATE"
    HARD = "HARD"
    VERY_HARD = "VERY_HARD"


class DifficultyClassification(StrEnum):
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MUCH_EASIER = "MUCH_EASIER"
    SLIGHTLY_EASIER = "SLIGHTLY_EASIER"
    COHERENT = "COHERENT"
    SLIGHTLY_HARDER = "SLIGHTLY_HARDER"
    MUCH_HARDER = "MUCH_HARDER"


class RuleStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


class ProgressionAction(StrEnum):
    ADVANCE = "ADVANCE"
    MAINTAIN = "MAINTAIN"
    REVIEW = "REVIEW"
    REINFORCE = "REINFORCE"
    RETURN_TO_PREREQUISITE = "RETURN_TO_PREREQUISITE"
    TEACHER_REVIEW = "TEACHER_REVIEW"
    COMPLETE_PATH = "COMPLETE_PATH"
    SUSPEND_ADAPTATION = "SUSPEND_ADAPTATION"


class ApprovalStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AdaptationType(StrEnum):
    PLAIN_LANGUAGE = "PLAIN_LANGUAGE"
    LARGE_PRINT = "LARGE_PRINT"
    HIGH_CONTRAST = "HIGH_CONTRAST"
    EASY_READING = "EASY_READING"
    IMAGE_DESCRIPTION = "IMAGE_DESCRIPTION"
    AUDIO_DESCRIPTION = "AUDIO_DESCRIPTION"
    SCREEN_READER = "SCREEN_READER"
    CAPTIONS = "CAPTIONS"
    REDUCED_VISUAL_STIMULUS = "REDUCED_VISUAL_STIMULUS"
    STEP_BY_STEP = "STEP_BY_STEP"
    VISUAL_SUPPORT = "VISUAL_SUPPORT"
    OBJECTIVE_INSTRUCTIONS = "OBJECTIVE_INSTRUCTIONS"
    KEYBOARD_NAVIGATION = "KEYBOARD_NAVIGATION"


class AccessibleVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class EquivalenceStatus(StrEnum):
    NOT_CHECKED = "NOT_CHECKED"
    PRESERVED = "PRESERVED"
    NEEDS_PEDAGOGICAL_REVIEW = "NEEDS_PEDAGOGICAL_REVIEW"
    NOT_EQUIVALENT = "NOT_EQUIVALENT"


class GenerationMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    MANUAL = "MANUAL"
    ASSISTED = "ASSISTED"
