apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: {name: educode, namespace: argocd}
spec:
  sourceRepos: ['https://github.com/ORGANIZATION/educode-infra.git']
  destinations:
    - {namespace: educode-*, server: https://kubernetes.default.svc}
  clusterResourceWhitelist:
    - {group: '*', kind: '*'}
